### ISSUE TITLE
Final checks and review for v0.1 to CRAN

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3proba#49]
* [x] Documentation consistency
* Maths in
  * [x] Graf score
  * [x] ILL
  * [x] Standard errors
  * [x] LearnerSurvParametric
  * [x] LearnerSurvFlexible
* [x] Suitable coverage (ideally at least 80%) (#47)
* [x] Readme (#46)
* [x] Remove, comment out, or note problems in survAUC (#43)
* [x] Either implemented a second variant of `crank` or document carefully (#42) 
* [x] User-test compositors

**Comment by RaphaelS1** [comment]
@mllg anything else required from your side before I send to CRAN?

**Comment by RaphaelS1** [comment]
@fkiraly there is a general question raised in `LearnerSurvParametric` as follows. By example say a user selects `dist = "gaussian"` and `form = aft`, then a log-normal model is fit using `survreg` which implicitly implies `aft` and then re-parameterised into `ph`. In terms of interpretation this is meaningless as the PH assumption doesn't hold for Normal distributions, but the result is still a valid probability distribution. I have chosen to proceed by adding a note that says "whilst any combination is possible it may not be interpretable" but should we prevent this from even occurring by dependent parameters?

Argument for: Stop uninterpretable results
Argument against: Could lead to a better result in a benchmark, or more likely it will be vastly inferior and thrown out in tuning immediately.

**Comment by fkiraly** [comment]
What is precisely the return and behaviour if you pass `dist = gaussian`?
It returns `distr` objects, but how precisely are these constructed, i.e., how does `lp` relate to parameters of the returned distribution?

**Comment by RaphaelS1** [comment]
`lp` is just defined by $X\beta$ where $\beta$ are the fitted coefficients and $X$ is newdata, so it doesn't matter which `form` is requested, the `lp` stays the same. The composition with `lp` however is just one of the three linear functions. So for `dist = gaussian` the parameters are estimated with a location-scale framework and cast into a `distr6` compatible parameterisation so in this case `Normal$new(mean = location, sd = scale)` then `lp = coeffs * newdata` (without intercept) and the `ph` form is calculated with `S(t) = S0(t)^exp(lp))` where in this case `S0` is the survival function of the fitted Normal distribution

**Comment by fkiraly** [comment]
So what is location, or scale?

**Comment by RaphaelS1** [comment]
Well in this case the location-scale parameterisation is the same as the mean-sd parameterisation

**Comment by RaphaelS1** [comment]
Moving all discussion about surv.parametric to #54
